# Generated by Django 4.1 on 2022-12-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.room"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(),
        ),
    ]
