# Generated by Django 4.1 on 2022-12-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_options_room_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="room",
            name="participants",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
